# .cpanel.yml for PHP site deployment
deployment:
  tasks:
    # Absolute path to your public_html folder (inside your cPanel user home)
    - export DEPLOY_DIR=/home/g8d9uc0f8e0i/public_html
    
    # Copy all files from repo to public_html, excluding .git
    - /usr/bin/rsync -av --exclude='.git' ./ $DEPLOY_DIR
# CHANGES