# .cpanel.yml
deployment:
  tasks:
    # Set the deployment directory to public_html
    - export DEPLOY_DIR=/home/g8d9uc0f8e0i/public_html

    # Copy all files from the repo to public_html, excluding .git
    - /usr/bin/rsync -av --exclude='.git' ./ $DEPLOY_DIR
#CHANGES IN COMMENT 