# .cpanel.yml for PHP site deployment
deployment:
  tasks:
    # Absolute path to your public_html folder
    - export DEPLOY_DIR=/home/skillednepali/public_html
    
    # Copy all files from repo to public_html, excluding .git
    - /usr/bin/rsync -av --exclude='.git' ./ $DEPLOY_DIR
